import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ContextReownAppKitProvider from "@/context/ReownAppKit";
import { headers } from "next/headers";
import { NotifyProvider } from "@/context/NotifyContext";
import { Toaster } from "sonner";
import QueryProviders from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const headersObj = await headers();
  const cookies = headersObj.get('cookie')

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ContextReownAppKitProvider cookies={cookies}>
          <NotifyProvider>
            <Toaster closeButton />
            <QueryProviders>
                {children}
            </QueryProviders>
          </NotifyProvider>
        </ContextReownAppKitProvider>
      </body>
    </html>
  );
}
